### ISSUE TITLE
Configuration to implement in Cake3?

### ISSUE THREAD

**Issue by barrychapman** [jippi/cakephp-newrelic#9]
I am seeing some of the instructions to implement this in cake do not apply to cake3.

Are there any instructions on how to do so?

Thanks!

**Comment by jippi** [comment]
Hi!

The setup are 90% the same as cake 2.x - you can find the 3.x version here https://github.com/jippi/cakephp-newrelic/tree/cake3

**Comment by barrychapman** [comment]
where does it end the transactions?
